timezone: Africa/Nairobi

title: Cynthia Kiptoo # the main title

tagline: Web Development| AI| Software Developer # it will display as the subtitle

description: >- # used by seo meta and the atom feed
  Software Developer with a focus on Web and AI. I build responsive web applications and integrate intelligent features to solve real-world problems through code.
  
# Fill in the protocol & hostname for your site.
# E.g. 'https://username.github.io', note that it does not end with a '/'.
url: "https://Chela662.github.io"

github:
  username: Chela662 # change to your GitHub username

# Twitter is commented out since you're not using it
# twitter:
#   username: Cynthia_Kiptoo # change to your Twitter username

social:
  # Change to your full name.
  # It will be displayed as the default author of the posts and the copyright owner in the Footer
  name: Cynthia Kiptoo
  email: kiptoocynthia7@gmail.com # change to your email address
  links:
    # The first element serves as the copyright owner's link
    - https://twitter.com/Cynthia_Kiptoo # change to your Twitter homepage
    - https://github.com/Chela662 # change to your GitHub homepage
    # Uncomment below to add more social links
    # - https://www.facebook.com/username
